(("default" . ((user-emacs-directory . "~/.emacs.d/emacs")))
 ("spacemacs" . ((user-emacs-directory . "~/.emacs.d/spacemacs")
                         (env . (("SPACEMACSDIR" . "~/.spacemacs.d")))))
 ("doom" . ((user-emacs-directory . "~/.emacs.d/doom-emacs")))
 ("doom-dev" . ((user-emacs-directory . "~/.emacs.d/doom-emacs-dev"))))
