{ pkgs, ... }: {
  homebrew = {
    taps = [
      "homebrew/cask-fonts"
      # "homebrew/cask"
    ];

    casks = [
      "1password"
      "alfred"
      "anki"
      "appcleaner"
      "arc"
      "blender"
      "chatwork"
      "dbeaver-community"
      "discord"
      "docker"
      "figma"
      "firefox"
      "flux"
      "font-hack-nerd-font"
      "font-hasklig"
      "font-roboto"
      "fork"
      "google-chrome"
      "google-drive"
      "google-japanese-ime"
      "heptabase"
      "httpie"
      "iterm2"
      "karabiner-elements"
      "kensingtonworks"
      "logseq"
      "microsoft-edge"
      "morgen"
      "mos"
      "multipass"
      "notion"
      "obsidian"
      "poe"
      "postman"
      "raindropio"
      "raycast"
      "readdle-spark"
      "scrivener"
      "slack"
      "spotify"
      "utm"
      "visual-studio-code"
      "wireshark"
      "workflowy"
      "zappy"
      "zoom"
      "zotero"
      # "asana"
      # "clickup"
      # "fluid"
      # "gyazo"
      # "krisp"
      # "notion"
      # "rambox"
    ];
  };
}
