{ pkgs, ... }: {
  homebrew = {
    taps = [
      # "homebrew/cask-fonts"
      # "homebrew/cask"
      "nikitabobko/tap"
    ];

    casks = [
      "1password"
      "aerospace"
      "alfred"
      "anki"
      "appcleaner"
      "arc"
      "bartender"
      "battery"
      "beeper"
      "bettertouchtool"
      "blender"
      "dbeaver-community"
      "discord"
      "docker"
      "figma"
      "firefox"
      "flux"
      "font-hack-nerd-font"
      "font-hasklig"
      "font-roboto"
      "fork"
      "google-chrome"
      "google-drive"
      "heptabase"
      "httpie"
      "iterm2"
      "karabiner-elements"
      "logi-options+"
      "logseq"
      "microsoft-edge"
      "miro"
      "mos"
      "multipass"
      "notion"
      "obsidian"
      "poe"
      "postman"
      "raindropio"
      "raycast"
      "readdle-spark"
      "slack"
      "spotify"
      "utm"
      "visual-studio-code"
      "wezterm"
      "wireshark"
      "workflowy"
      "zappy"
      "zoom"
      "zotero"
      # "asana"
      # "chatwork"
      # "clickup"
      # "fluid"
      # "google-japanese-ime"
      # "gyazo"
      # "kensingtonworks"
      # "krisp"
      # "morgen"
      # "notion"
      # "rambox"
      # "scrivener"
    ];
  };
}
