{ pkgs, ... }: {
  homebrew = {
    taps = [
      # "homebrew/cask-fonts"
      # "homebrew/cask"
      "nikitabobko/tap"
    ];

    casks = [
      "1password"
      "aerospace"
      "anki"
      "appcleaner"
      "arc"
      "battery"
      "beeper"
      "bettertouchtool"
      "blender"
      "chatgpt"
      "claude"
      "cursor"
      "dbeaver-community"
      "deepl"
      "deskpad"
      "discord"
      "docker"
      "figma"
      "firefox"
      "flashspace"
      "flux"
      "font-hack-nerd-font"
      "font-hasklig"
      "font-roboto"
      "fork"
      "google-chrome"
      "google-drive"
      "google-japanese-ime"
      "heptabase"
      "httpie"
      "istat-menus"
      "iterm2"
      "jordanbaird-ice"
      "karabiner-elements"
      "leader-key"
      "logi-options+"
      "logseq"
      "microsoft-edge"
      "miro"
      "mos"
      "multipass"
      "notion"
      "obsidian"
      "poe"
      "popclip"
      "postman"
      "raycast"
      "readdle-spark"
      "slack"
      "spotify"
      "utm"
      "visual-studio-code"
      "wezterm"
      "wireshark"
      "zappy"
      "zoom"
      "zotero"
      # "alfred"
      # "asana"
      # "chatwork"
      # "clickup"
      # "fluid"
      # "gyazo"
      # "kensingtonworks"
      # "krisp"
      # "morgen"
      # "notion"
      # "raindropio"
      # "rambox"
      # "scrivener"
      # "workflowy"
    ];
  };
}
